import resume1 from "./SirishaResume.pdf"
import resume2 from "./KiranKumar_Resume.pdf"


export const resumeAsserts=[
    {
        noPages:2,
        resume:{resume1},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
    {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
    {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
    {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
    {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
    {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
    {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },

    {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
    {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
    {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
     {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
    {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
     {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
     {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
     {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
     {
        noPages:1,
        resume:{resume2},
        image:"https://i.postimg.cc/dQkRqM6w/Capture.png"
    },
]